agents/builtin/mysql/slowlog/slowlog.go

https://jira.percona.com/browse/PMM-3900

PMM-3900 Skip unknown system variable.

---

actions/concurrent_runner_test.go

```
==================
WARNING: DATA RACE
Read at 0x00c000152130 by goroutine 38:
runtime.chansend()
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/chan.go:142 +0x0
github.com/percona/pmm-agent/actions.(*ConcurrentRunner).run()
/Users/aleksi/Code/Percona/PMM-2.0/src/github.com/percona/pmm-agent/actions/concurrent_runner.go:107 +0x596
Previous write at 0x00c000152130 by goroutine 37:
runtime.closechan()
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/chan.go:334 +0x0
github.com/percona/pmm-agent/actions.NewConcurrentRunner.func1()
/Users/aleksi/Code/Percona/PMM-2.0/src/github.com/percona/pmm-agent/actions/concurrent_runner.go:67 +0x76
Goroutine 38 (running) created at:
github.com/percona/pmm-agent/actions.(*ConcurrentRunner).Start() …
```

PMM-3978 Show data race problem.

---

agents/builtin/mongodb/internal/profiler/profiler_test.go
agents/builtin/mongodb/mongodb_test.go
connectionchecker/connection_checker_test.go
docker-compose.yml

* Avoid PostgreSQL port clash with pmm-managed.
* Be explicit about MongoDB user.

Change dev environment.

---

Gopkg.lock
Gopkg.toml
actions/mysql_explain_action_test.go
actions/mysql_show_create_table_action.go
actions/mysql_show_create_table_action_test.go
actions/mysql_show_index_action.go
actions/mysql_show_index_action_test.go
actions/mysql_show_table_status_action_test.go
utils/tests/db.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_explain_action_responses.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_explain_json_action_responses.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_explain_traditional_json_action_responses.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_show_create_table_action_responses.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_show_index_action_responses.go
vendor/github.com/percona/pmm/api/managementpb/json/client/actions/start_my_sql_show_table_status_action_responses.go

PMM-4189 Add tests for SQL injections.

---

agents/mysql/slowlog/slowlog.go

https://jira.percona.com/browse/PMM-4298
https://github.com/Percona-Lab/pmm-submodules/pull/378

PMM-4298 Add datadir path if slowlog path is relative.

---

agents/mongodb/internal/profiler/collector/collector.go

There was `context deadline error` because `connectAndCollect()` was called every second in the cycle and was using the same context. So I have moved context inside this function, so now every call of the function are using different context.

PMM-4464 Fix context deadline error.

---

.travis.yml

Tested locally with go version go1.13.4 linux/amd64

PMM-4010 Go 1.13.x inn travis

---

actions/mongodb_query_admincommand_action.go
actions/mongodb_query_admincommand_action_test.go
actions/mysql_query_show_action_test.go

Tests fail with MariaDB 10.4.13 due to bug in their image: https://jira.mariadb.org/browse/MDEV-22542

SAAS-140 Skip timestamp fields for now.

---

connectionchecker/connection_checker_test.go
docker-compose.yml
utils/tests/postgresql.go

There is no port clash with pmm-managed anymore because it uses devcontainer.

Use standard port for PostgreSQL.

---

Gopkg.lock
Gopkg.toml

PMM-6378 Update toolkit version

---

.golangci.yml
agents/postgres/pgstatmonitor/models.go
agents/postgres/pgstatmonitor/pgstatmonitor.go
agents/postgres/pgstatmonitor/pgstatmonitor_test.go
agents/postgres/pgstatmonitor/stat_monitor_cache.go
agents/postgres/pgstatstatements/pgstatstatements_test.go

https://github.com/Percona-Lab/pmm-submodules/pull/1152

PMM-6642 Align PG Stat monitor with buckets.

---

actions/postgresql_show_create_table_action.go
actions/postgresql_show_create_table_action_test.go
actions/postgresql_show_index_action.go
actions/postgresql_show_index_action_test.go

https://github.com/Percona-Lab/pmm-submodules/pull/1169

PMM-6765 Handle schema names.

---

agents/postgres/pgstatmonitor/pgstatmonitor.go

https://github.com/Percona-Lab/pmm-submodules/pull/1172

PMM-6769 Fix units for CPU times.

---

Gopkg.lock
Gopkg.toml

* https://github.com/percona/pmm/pull/595
* https://github.com/percona/pmm-managed/pull/492
* https://github.com/percona/pmm-agent/pull/199
https://github.com/Percona-Lab/pmm-submodules/pull/1180
Safe for the patch release

PMM-6760 Update protobuf

---

agentlocal/agent_local.go
commands/clients.go
commands/setup.go
config/config.go
config/config_test.go

On top of https://github.com/percona/pmm-agent/pull/201.
https://github.com/Percona-Lab/pmm-submodules/pull/1228

PMM-6825 Add --listen-address flag

---

actions/mysql_explain_action.go
actions/mysql_explain_action_test.go

It might be destructive to use EXPLAIN in MySQL because stored
functions and procedures are being called.
Now, we wrap EXPLAIN in transaction so we can rollback any
changes after EXPLAIN is done.

PMM-6993 Run EXPLAIN queries in transaction

---

.github/workflows/go.yml
agents/postgres/pgstatmonitor/models.go
agents/postgres/pgstatmonitor/models_reform.go
agents/postgres/pgstatmonitor/pgstatmonitor.go
agents/postgres/pgstatmonitor/pgstatmonitor_test.go
agents/postgres/pgstatmonitor/stat_monitor_cache.go

https://jira.percona.com/browse/PMM-7569

PMM-7569 PG monitor 0.8.

---

client/client.go
go.mod
go.sum
jobs/mysql_backup_job.go

[PMM-7386](https://jira.percona.com/browse/PMM-7386)
- PMM-managed - https://github.com/percona/pmm-managed/pull/699
- API - https://github.com/percona/pmm/pull/709

PMM-7386 MySQL Backup job

---

config/config.go

https://jira.percona.com/browse/PMM-8083

PMM-8083 Check if config file exists

---

agents/mongodb/internal/profiler/collector/collector.go

3rd party contribution. I am just making a PR from the patch file provided in the ticket. 
Jira: https://jira.percona.com/browse/PMM-7910

PMM-7910 Query collector never recovers

---

agents/mysql/slowlog/slowlog.go

Ticket: https://jira.percona.com/browse/PMM-7104
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1762

PMM-7104 dont rotate binlogs

---

commands/clients.go
config/config.go

https://jira.percona.com/browse/PMM-6778
pmm-admin: https://github.com/percona/pmm-admin/pull/153
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1772

PMM-6778: add custom labels to config command

---

client/client.go
go.mod
go.sum
jobs/mongodb_backup_job.go
jobs/mongodb_restore_job.go

[PMM-7568](https://jira.percona.com/browse/PMM-7568)
---

PMM-7568 MongoDB backup restores

---

jobs/mysql_backup_job.go
jobs/mysql_restore_job.go

https://jira.percona.com/browse/PMM-8613
Build: https://github.com/Percona-Lab/pmm-submodules/pull/1987

PMM-8613 Mysql decompress using xtrabackup

---

client/channel/channel.go
go.mod
go.sum

[PMM-9169](https://jira.percona.com/browse/PMM-9169)
API PR: https://github.com/percona/pmm/pull/797
managed PR: https://github.com/percona/pmm-managed/pull/868
FB: https://github.com/Percona-Lab/pmm-submodules/pull/2149

PMM-9169: Add primitive binary type

---

.whitesource

[SAAS-800](https://jira.percona.com/browse/SAAS-800)

SAAS-800 Integrate WhiteSource

---

actions/mysql_query_show_action_test.go
go.mod
go.sum
packages.dot
utils/version/mysql.go
utils/version/mysql_test.go

[PMM-8203](https://jira.percona.com/browse/PMM-8203) : Unknown column 'performance_schema.events_statements_summary_by_digest.QUERY_SAMPLE_TEXT' in 'field list'
Build: [SUBMODULES-2360](https://github.com/Percona-Lab/pmm-submodules/pull/2360)

PMM-8203 Fixed MySQL version & flavor detection

---

actions/mongodb_query_admincommand_action_test.go
actions/mysql_query_show_action_test.go
actions/mysql_show_table_status_action_test.go
actions/postgresql_show_create_table_action.go
agents/supervisor/supervisor_test.go
client/channel/channel_test.go
client/client.go
docker-compose.yml
go.mod
go.sum
utils/tests/mongodb.go

PMM-9473
Build: SUBMODULES-2347

PMM-9473 Extend MongoDB checks.
